module.exports = {
    nineS: {
        dataCamouflageComplete: 'Generación de datos Mock completada',
        scanningField: 'Analizando diferencias entre campos Frontend/Backend... Ejecutando puente semántico',
        dataCamouflage: fileName => `Atravesando el firewall del objetivo... Ejecutando protocolo de camuflaje de datos [${fileName}]`,
    },
    pod042: {
        extractingUiMetadata: 'Extrayendo metadatos de UI desde la red neuronal en la nube...',
        simulate: 'Solicitud real interceptada. Desplegando paquete simulado estándar: example.json',
        queueEmpty: 'Cola vacía. Sincronizando configuración de rutas Menu con Bunker...',
        uploadVisualMetadata: 'Subiendo metadatos visuales al centro de comando para análisis semántico...',
        visualPartCaptured: 'Fragmento visual detectado. Ejecutando protocolo de construcción fragmentada...',
        partialConstruction: time => `Informe: construcción parcial completada. Tiempo: ${time}s`,
        partialRecommendation: '│ Recomendación: ensamble manualmente el bloque de código anterior en el archivo objetivo',
        constructionAborted: virus => `Construcción abortada. Virus lógico o tiempo de conexión agotado: ${virus}`,
        partialConstructionAborted: virus => `[Advertencia] Fallo en construcción fragmentada. Interferencia lógica detectada: ${virus}`,
        visualCaptured: fileName => `Captura visual completada: [${fileName}]. Asignando recursos del Bunker para construcción física...`,
        intercept: fileName => `El módulo [${fileName}] ya existe en la base de datos del Bunker. Protocolo omitido para evitar sobrescritura`,
        assemblyComplete: (fileName, time) => `Protocolo de construcción finalizado. Módulo [${fileName}] ensamblado físicamente. Tiempo: ${time}s`,
    },
    pod153: {
        signalLinkFault: virus => `Fallo en enlace de señal: ${virus}`,
        formatError: 'Formato JSON no estándar detectado. Intentando alineación de datos originales',
        autonomousAddressing: 'Iniciando protocolo de direccionamiento autónomo multicanal [versión semántica]...',
        signalSynchronized: count => `Sincronización completada. ${count} nodos activados`,
        alignmentFailed: virus => `Fallo de alineación. Los datos de interfaz encontraron un firewall: ${virus}`,
        inactiveModule: fileName => `Módulo sin energía detectado [${fileName}]. Solicitando análisis de precisión a 9S`,
        capturedRuntimeSignal: fileName => `Señal en ejecución capturada [${fileName}]. Ejecutando alineación automática...`,
        reconEncryptedData: fileName => `Fuente de datos cifrada detectada [${fileName}]. Intentando alineación semántica...`,
        unknownModule: fileName => `No se encontró recurso del módulo [${fileName}] en Bunker. Ejecute primero la construcción visual`,
        bridgeProtocolComplete: (count, time) => `Protocolo puente semántico completado. ${count} diferencias corregidas. Tiempo: ${time}s`,
    },

    bunker: {
        exit: 'Señal del sistema perdida...',
        envCopy: 'Archivo .env almacenado correctamente',
        argDesc: 'Especificar plantilla del framework frontend',
        systemStandby: 'Sistema en espera...',
        desc: 'Generador de código CRUD frontend impulsado por IA',
        configCopy: 'Archivo config.js almacenado correctamente',
        initDesc: 'Inicializar entorno de construcción Bunker en el directorio actual',
        envCheck: 'Archivo .env existente detectado. Saltando creación',
        dataSynced: 'Todos los datos de construcción sincronizados con el nodo Bunker',
        configCheck: 'Archivo config.js existente detectado. Saltando creación',
        linkSevered: 'Conexión perdida: revise la red o la resonancia de Black Box',
        systemOffline: 'Desconectando enlace neural en la nube. Ejecutando sellado físico de datos...',
        copyTemplateError: virus => `Fallo en construcción de plantilla: ${virus}`,
        star: 'Si este proyecto te ayuda, deja una estrella en GitHub ⭐',
        towerOnline: port => `Torre de interceptación de señales activa [Frecuencia: ${port}]`,
        watchDesc: 'Iniciar monitorización completa: construcción coordinada Page/Part/API',
        accessDenied: 'Acceso denegado: API Key inválida o límite agotado',
        disclaimer: 'Los resultados son referencias. Cada unidad debe ajustar según la situación real',
        towerConnected: port => `Comando: apunta tu proxy hacia http://localhost:${port}`,
        networkInstability: count => `Inestabilidad de red neuronal. Reintentando conexión... (${count})`,
        frameworkNotSupported: template => `Framework [${template}] no soportado. Pull Requests son bienvenidos`,
        initComplete: cmd => `Despliegue del Bunker completado. Añade ${cmd} a package.json scripts`,
    },
    operator6O: {
        call2B: 'Llamando a 2B. Monitorización global del Bunker lista!',
    }
}