module.exports = {
    nineS: {
        dataCamouflageComplete: 'Génération des données Mock terminée',
        scanningField: 'Analyse des différences de champs Frontend/Backend en cours... Activation du pont sémantique',
        dataCamouflage: fileName => `Percée du pare-feu cible en cours... Exécution du protocole de camouflage des données [${fileName}]`,
    },
    pod042: {
        extractingUiMetadata: 'Extraction des métadonnées UI depuis le réseau neuronal cloud...',
        simulate: 'Requête réelle détectée. Déploiement du paquet de simulation standard : example.json',
        queueEmpty: 'File d’attente vide. Synchronisation de la configuration des routes Menu avec le Bunker...',
        uploadVisualMetadata: 'Transmission des métadonnées visuelles au quartier général. Analyse sémantique en cours...',
        visualPartCaptured: 'Fragment visuel local détecté. Activation du « protocole de construction fragmentaire »...',
        partialConstruction: time => `Rapport : Construction partielle terminée. Durée : ${time}s`,
        partialRecommendation: '│ Recommandation : veuillez intégrer manuellement le bloc de code ci-dessus dans le fichier cible',
        constructionAborted: virus => `Construction interrompue. Virus logique ou délai de connexion dépassé détecté : ${virus}`,
        partialConstructionAborted: virus => `[Avertissement] Échec de la construction fragmentaire. Interférence logique détectée : ${virus}`,
        visualCaptured: fileName => `Capture visuelle terminée : [${fileName}]. Déploiement des ressources du Bunker et lancement de la construction physique...`,
        intercept: fileName => `Le module [${fileName}] existe déjà dans la base de données du Bunker. Protocole interrompu pour éviter l’écrasement`,
        assemblyComplete: (fileName, time) => `Protocole de construction terminé. Module [${fileName}] assemblé avec succès. Durée : ${time}s`,
    },
    pod153: {
        signalLinkFault: virus => `Erreur de liaison du signal : ${virus}`,
        formatError: 'Format JSON non standard détecté. Tentative de synchronisation avec les données brutes',
        autonomousAddressing: 'Activation du « protocole d’adressage automatique multi-canaux [version analyse sémantique] »...',
        signalSynchronized: count => `${count} nœuds synchronisés. Alimentation confirmée`,
        alignmentFailed: virus => `Échec de synchronisation du signal. Les données API sont bloquées par un pare-feu puissant : ${virus}`,
        inactiveModule: fileName => `Module non activé détecté [${fileName}]. Analyse haute précision demandée à 9S`,
        capturedRuntimeSignal: fileName => `Signal d’exécution intercepté [${fileName}]. Activation du protocole d’alignement automatique...`,
        reconEncryptedData: fileName => `Source de données chiffrées détectée [${fileName}]. Tentative du protocole d’alignement sémantique...`,
        unknownModule: fileName => `Aucune ressource du module [${fileName}] trouvée dans la base du Bunker. Veuillez effectuer la construction visuelle au préalable`,
        bridgeProtocolComplete: (count, time) => `Protocole de pont sémantique terminé. ${count} différences de champs corrigées. Durée : ${time}s`,
    },
    bunker: {
        exit: 'Signal système perdu...',
        envCopy: 'Stockage .env terminé',
        argDesc: 'Spécifier le modèle du framework frontend',
        systemStandby: 'Système en mode veille...',
        desc: 'Générateur de code CRUD frontend piloté par IA',
        configCopy: 'Stockage de config.js terminé',
        initDesc: 'Initialiser l’environnement de construction du Bunker dans le répertoire actuel',
        envCheck: 'Fichier .env existant détecté. Génération ignorée',
        dataSynced: 'Toutes les données de construction ont été synchronisées avec le nœud de stockage du Bunker',
        configCheck: 'Fichier config.js existant détecté. Génération ignorée',
        linkSevered: 'Connexion interrompue : veuillez vérifier le réseau ou la résonance de la boîte noire',
        systemOffline: 'Déconnexion du réseau neuronal cloud. Scellement physique des données en cours...',
        copyTemplateError: virus => `Échec de construction du modèle : ${virus}`,
        star: 'Si ce système vous fait gagner du temps, pensez à lui donner une étoile sur GitHub ⭐',
        towerOnline: port => `Tour d’interception des signaux en ligne [Fréquence : ${port}]`,
        watchDesc: 'Démarrer la surveillance multi-canaux : construction coordonnée Page/Part/API',
        accessDenied: 'Accès au quartier général refusé : clé API invalide ou quota épuisé',
        disclaimer: 'Les résultats de correspondance sont fournis à titre indicatif. Chaque unité doit effectuer son propre ajustement selon son environnement',
        towerConnected: port => `Ordre : configurez votre cible proxy vers http://localhost:${port}`,
        copyEnum: '│ Informations génétiques Backend (Enum) détectées\n│ Recommandation : intégrer manuellement le fragment de code ci-dessous dans le module ressource',
        networkInstability: count => `Connexion au cloud neuronal instable. Nouvelle tentative en cours... (tentative ${count})`,
        frameworkNotSupported: template => `Framework [${template}] actuellement non supporté. Les Pull Requests sont bienvenues`,
        strategicThreshold: (target, current) => `Le nombre de clones physiques a dépassé le seuil stratégique ${target} ! Puissance actuelle : ${current}`,
        initComplete: cmd => `Déploiement du Bunker terminé. Pour un accès plus rapide au champ de bataille, ajoutez manuellement ${cmd} aux scripts de package.json`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement
            ? 'Félicitations, Commandant. Votre protocole de construction fait désormais partie de la gloire de l’humanité'
            : `Nombre actuel de constructions : ${current}. Encore ${target - current} unités avant l’obtention de la médaille`,
    },
    operator6O: {
        call2B: 'Communication vers 2B : la surveillance multi-canaux du Bunker est opérationnelle !',
    }
}