module.exports = {
    nineS: {
        dataCamouflageComplete: 'Pembuatan data Mock berhasil',
        scanningField: 'Memindai perbedaan field Frontend/Backend... Menjalankan protokol jembatan semantik',
        dataCamouflage: fileName => `Menembus firewall target... Menjalankan protokol penyamaran data [${fileName}]`,
    },
    pod042: {
        extractingUiMetadata: 'Mengekstrak metadata UI dari jaringan saraf cloud...',
        simulate: 'Permintaan nyata terdeteksi. Menurunkan paket simulasi standar: example.json',
        queueEmpty: 'Antrian kosong. Sinkronisasi konfigurasi Menu dengan Bunker...',
        uploadVisualMetadata: 'Mengirim metadata visual ke pusat komando untuk analisis semantik...',
        visualPartCaptured: 'Sampel visual terdeteksi. Menjalankan protokol konstruksi fragmen...',
        partialConstruction: time => `Laporan: konstruksi parsial selesai. Waktu: ${time}s`,
        partialRecommendation: '│ Rekomendasi: Pasang blok kode di atas secara manual ke file target',
        constructionAborted: virus => `Konstruksi dihentikan. Virus logika atau batas waktu koneksi terdeteksi: ${virus}`,
        partialConstructionAborted: virus => `[Peringatan] Konstruksi fragmen gagal. Gangguan logika terdeteksi: ${virus}`,
        visualCaptured: fileName => `Penangkapan visual selesai: [${fileName}]. Menyiapkan sumber daya Bunker untuk konstruksi fisik...`,
        intercept: fileName => `Modul [${fileName}] sudah ada dalam database Bunker. Protokol dilewati untuk mencegah penimpaan`,
        assemblyComplete: (fileName, time) => `Protokol konstruksi selesai. Modul [${fileName}] berhasil dirakit secara fisik. Waktu: ${time}s`,
    },
    pod153: {
        signalLinkFault: virus => `Gangguan koneksi sinyal: ${virus}`,
        formatError: 'Format JSON tidak standar. Mencoba penyelarasan data mentah',
        autonomousAddressing: 'Memulai protokol pengalamatan otomatis multi-kanal [versi semantik]...',
        signalSynchronized: count => `Sinkronisasi sinyal selesai. ${count} node telah diaktifkan`,
        alignmentFailed: virus => `Penyelarasan sinyal gagal. Data API menghadapi firewall: ${virus}`,
        inactiveModule: fileName => `Modul tidak aktif ditemukan [${fileName}]. Meminta analisis presisi tinggi dari 9S`,
        capturedRuntimeSignal: fileName => `Sinyal runtime tertangkap [${fileName}]. Menjalankan penyelarasan otomatis...`,
        reconEncryptedData: fileName => `Sumber data terenkripsi ditemukan [${fileName}]. Mencoba protokol penyelarasan semantik...`,
        unknownModule: fileName => `Resource modul [${fileName}] tidak ditemukan dalam database Bunker. Jalankan konstruksi visual terlebih dahulu`,
        bridgeProtocolComplete: (count, time) => `Protokol jembatan semantik selesai. ${count} perbedaan field telah diperbaiki. Waktu: ${time}s`,
    },
    bunker: {
        exit: 'Sinyal sistem telah hilang...',
        envCopy: 'File .env berhasil disimpan',
        argDesc: 'Menentukan template framework frontend',
        systemStandby: 'Sistem dalam mode standby...',
        desc: 'Generator kode CRUD frontend berbasis AI',
        configCopy: 'File config.js berhasil disimpan',
        initDesc: 'Menginisialisasi lingkungan konstruksi Bunker di direktori saat ini',
        envCheck: 'File .env sudah tersedia. Pembuatan dilewati',
        dataSynced: 'Seluruh data konstruksi telah disinkronkan dengan node penyimpanan Bunker',
        configCheck: 'File config.js sudah tersedia. Pembuatan dilewati',
        linkSevered: 'Koneksi terputus: periksa jaringan atau resonansi Black Box',
        systemOffline: 'Memutus koneksi neural cloud. Menjalankan penyegelan fisik data...',
        copyTemplateError: virus => `Konstruksi template gagal: ${virus}`,
        star: 'Jika proyek ini membantu menghemat waktu Anda, berikan bintang di GitHub ⭐',
        towerOnline: port => `Menara intersepsi sinyal aktif [Frekuensi: ${port}]`,
        watchDesc: 'Mengaktifkan pemantauan multi-kanal: konstruksi Page/Part/API terpadu',
        accessDenied: 'Akses ditolak pusat komando: API Key tidak valid atau kuota habis',
        disclaimer: 'Hasil pencocokan hanya sebagai referensi. Setiap unit harus menyesuaikan dengan kondisi nyata',
        towerConnected: port => `Perintah: arahkan target proxy Anda ke http://localhost:${port}`,
        copyEnum: '│ Kode genetik backend asli (Enum) terdeteksi\n│ Rekomendasi: pasang potongan kode berikut ke pusat resource modul',
        networkInstability: count => `Jaringan neural cloud tidak stabil. Mencoba koneksi ulang... (percobaan ${count})`,
        frameworkNotSupported: template => `Framework [${template}] belum didukung. Pull Request sangat diterima`,
        strategicThreshold: (target, current) => `Jumlah konstruksi telah melewati ambang strategis ${target}! Kekuatan saat ini: ${current}`,
        initComplete: cmd => `Deploy Bunker selesai. Tambahkan ${cmd} ke scripts package.json untuk akses lebih cepat`,
        isLegendary: (unlockAchievement, current, target) =>
            unlockAchievement
                ? 'Selamat komandan. Protokol konstruksi Anda telah menjadi bagian dari kejayaan umat manusia'
                : `Jumlah konstruksi saat ini: ${current}. Tersisa ${target - current} operasi menuju medali`,
    },
    operator6O: {
        call2B: 'Memanggil 2B. Sistem pemantauan seluruh kanal Bunker siap!',
    }
}