module.exports = {
    nineS: {
        dataCamouflageComplete: 'Generazione dati Mock completata',
        scanningField: 'Analisi delle differenze tra campi Frontend/Backend... Avvio del ponte semantico',
        dataCamouflage: fileName => `Superamento del firewall del bersaglio... Avvio protocollo di camuffamento dati [${fileName}]`,
    },
    pod042: {
        capturedToast: 'Intelligence visiva catturata. Avvio trasmissione...',
        startScout: 'Attivazione modalità [Istantanea Tattica con Tasto Destro]...',
        extractingUiMetadata: 'Estrazione dei metadati UI dalla rete neurale cloud...',
        partialConstruction: time => `Rapporto: costruzione parziale completata. Tempo: ${time}s`,
        uploadVisualMetadata: 'Invio metadati visivi al comando centrale per analisi semantica...',
        simulate: 'Richiesta reale intercettata. Lancio pacchetto simulato standard: example.json',
        visualPartCaptured: 'Frammento visivo rilevato. Avvio protocollo di costruzione frammentata...',
        capturedPage: pageName => `Pagina catturata [${pageName}] -> Trasferita nella directory screenShot`,
        partialRecommendation: '│ Raccomandazione: integra manualmente il blocco di codice sopra nel file destinazione',
        constructionAborted: virus => `Costruzione interrotta. Rilevato virus logico o timeout di connessione: ${virus}`,
        partialConstructionAborted: virus => `[Avviso] Fallimento costruzione frammentata. Interferenza logica rilevata: ${virus}`,
        scoutReady: '[Modalità Istantanea Tasto Destro Pronta] Fai clic con il tasto destro in un punto qualsiasi della pagina web.',
        visualCaptured: fileName => `Cattura visiva completata: [${fileName}]. Allocazione risorse del Bunker per costruzione fisica...`,
        intercept: fileName => `Il modulo [${fileName}] esiste già nel database del Bunker. Protocollo saltato per evitare sovrascrittura`,
        assemblyComplete: (fileName, time) => `Protocollo di costruzione completato. Modulo [${fileName}] assemblato fisicamente. Tempo: ${time}s, Sincronizzazione configurazione Menu con il Bunker...`,
    },
    pod153: {
        signalLinkFault: virus => `Errore collegamento segnale: ${virus}`,
        formatError: 'Formato JSON non standard. Tentativo di allineamento dati originali',
        signalSynchronized: count => `Sincronizzazione completata. ${count} nodi attivati`,
        alignmentFailed: virus => `Allineamento fallito. I dati API hanno incontrato un firewall: ${virus}`,
        autonomousAddressing: 'Avvio protocollo di indirizzamento autonomo multicanale [versione semantica]...',
        inactiveModule: fileName => `Modulo inattivo rilevato [${fileName}]. Richiesta analisi ad alta precisione da 9S`,
        capturedRuntimeSignal: fileName => `Segnale runtime intercettato [${fileName}]. Avvio allineamento automatico...`,
        reconEncryptedData: fileName => `Sorgente dati crittografata rilevata [${fileName}]. Tentativo di allineamento semantico...`,
        unknownModule: fileName => `Risorsa del modulo [${fileName}] non trovata nel database Bunker. Eseguire prima la costruzione visiva`,
        bridgeProtocolComplete: (count, time) => `Protocollo ponte semantico completato. Corrette ${count} differenze nei campi. Tempo: ${time}s`,
    },
    bunker: {
        envCopy: 'File .env salvato',
        exit: 'Segnale di sistema perso...',
        configCopy: 'File config.js salvato',
        systemStandby: 'Sistema in standby...',
        envCheck: 'File .env già presente. Creazione ignorata',
        desc: 'Generatore di codice CRUD frontend basato su IA',
        argDesc: 'Specificare il template del framework frontend',
        configCheck: 'File config.js già presente. Creazione ignorata',
        dataSynced: 'Tutti i dati di costruzione sincronizzati con il nodo Bunker',
        copyTemplateError: virus => `Errore nella costruzione del template: ${virus}`,
        watchDesc: 'Avvia monitoraggio completo: costruzione coordinata Page/Part/API',
        initDesc: 'Inizializza ambiente di costruzione Bunker nella directory corrente',
        star: 'Se questo progetto ti fa risparmiare tempo, lascia una stella su GitHub ⭐',
        towerOnline: port => `Torre di intercettazione segnali online [Frequenza: ${port}]`,
        linkSevered: 'Connessione interrotta: controllare rete o risonanza della Black Box',
        towerConnected: port => `Comando: indirizzare il proxy verso http://localhost:${port}`,
        accessDenied: 'Accesso negato dal comando centrale: API Key non valida o limite esaurito',
        systemOffline: 'Disconnessione collegamento neurale cloud. Avvio sigillatura fisica dei dati...',
        frameworkNotSupported: template => `Framework [${template}] non supportato. Pull Request benvenute`,
        disclaimer: 'I risultati sono solo suggerimenti. Ogni unità deve adattare secondo la situazione reale',
        networkInstability: count => `Instabilità rete neurale cloud. Tentativo di riconnessione... (${count})`,
        initComplete: cmd => `Distribuzione Bunker completata. Aggiungere ${cmd} agli script di package.json per accesso rapido`,
        strategicThreshold: (target, current) => `Il numero di costruzioni ha superato la soglia strategica ${target}! Potenza attuale: ${current}`,
        copyEnum: '│ Rilevato codice genetico originale Backend (Enum)\n│ Raccomandazione: saldare manualmente il frammento nel centro risorse del modulo',
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? 'Congratulazioni comandante. Il tuo protocollo di costruzione è diventato parte della gloria dell’umanità' : `Costruzioni attuali: ${current}. Mancano ${target - current} operazioni per ottenere la medaglia`,
    },
    operator6O: {
        call2B: 'Chiamata a 2B. Monitoraggio globale dei canali Bunker pronto!',
    }
}