module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mock 데이터 생성 완료',
        scanningField: 'Frontend/Backend 필드 차이 스캔 중... 시맨틱 브리지 프로토콜 실행',
        dataCamouflage: fileName => `대상 방화벽 돌파 중... 데이터 위장 프로토콜 실행 [${fileName}]`,
    },
    pod042: {
        startScout: '[우클릭 즉시 스냅샷] 모드 가동 중...',
        capturedToast: '시각 정보 획득 완료. 전송을 시작합니다...',
        simulate: '실제 요청 감지. 표준 시뮬레이션 패키지 투입: example.json',
        visualPartCaptured: '부분 시각 샘플 감지. "파편 구축 프로토콜" 실행...',
        extractingUiMetadata: '뉴럴 클라우드 네트워크에서 UI 메타데이터 추출 중...',
        uploadVisualMetadata: '시각 메타데이터를 본부로 전송 중. 시맨틱 분석 시작...',
        partialConstruction: time => `보고: 부분 구축 완료. 소요 시간: ${time}s`,
        partialRecommendation: '│ 권장: 아래 코드 블록을 대상 파일에 수동으로 통합하십시오',
        partialConstructionAborted: virus => `[경고] 파편 구축 실패. 논리 간섭 감지: ${virus}`,
        constructionAborted: virus => `구축 중단. 논리 바이러스 또는 연결 시간 초과 감지: ${virus}`,
        capturedPage: pageName => `페이지 획득 [${pageName}] -> screenShot 디렉터리로 전송 완료`,
        scoutReady: '[우클릭 스냅샷 모드 준비 완료] 브라우저 페이지 임의의 위치에서 [우클릭] 시 즉시 캡처됩니다.',
        visualCaptured: fileName => `시각 센서 캡처 완료: [${fileName}]. Bunker 자원을 배치하여 물리 구축 시작...`,
        intercept: fileName => `모듈 [${fileName}]은(는) 이미 Bunker 데이터베이스에 존재합니다. 덮어쓰기를 방지하기 위해 구축 프로토콜을 건너뜁니다`,
        assemblyComplete: (fileName, time) => `구축 프로토콜 완료. 모듈 [${fileName}] 물리적 장착 성공. 소요 시간: ${time}s, Bunker에 Menu 라우팅 설정 동기화 중...`,
    },
    pod153: {
        signalLinkFault: virus => `신호 연결 오류: ${virus}`,
        formatError: '비표준 JSON 형식 감지. 원본 데이터 정렬 시도',
        signalSynchronized: count => `${count}개의 노드 동기화 완료. 전원 활성화 확인`,
        autonomousAddressing: '「전 채널 자동 주소 지정 프로토콜 [시맨틱 스캔 버전]」 실행...',
        inactiveModule: fileName => `비활성 모듈 [${fileName}] 발견. 9S 고정밀 분석 요청`,
        alignmentFailed: virus => `신호 정렬 실패. API 데이터가 강력한 방화벽에 의해 차단됨: ${virus}`,
        reconEncryptedData: fileName => `암호화 데이터 소스 [${fileName}] 발견. 시맨틱 정렬 시도...`,
        capturedRuntimeSignal: fileName => `런타임 신호 [${fileName}] 포착. 자동 정렬 프로토콜 실행...`,
        bridgeProtocolComplete: (count, time) => `시맨틱 브리지 프로토콜 완료. ${count}개의 필드 차이 수정. 소요 시간: ${time}s`,
        unknownModule: fileName => `Bunker 데이터베이스에서 [${fileName}] 모듈 리소스를 찾을 수 없습니다. 먼저 시각 구축을 실행하십시오`,
    },
    bunker: {
        exit: '시스템 신호 손실...',
        envCopy: '.env 저장 완료',
        configCopy: 'config.js 저장 완료',
        systemStandby: '시스템 대기 상태...',
        argDesc: 'Frontend 프레임워크 템플릿 지정',
        desc: 'AI 기반 Frontend CRUD 코드 생성기',
        envCheck: '기존 .env 파일 발견. 생성을 건너뜁니다',
        initDesc: '현재 디렉터리에 Bunker 구축 환경 초기화',
        configCheck: '기존 config.js 파일 발견. 생성을 건너뜁니다',
        copyTemplateError: virus => `템플릿 구축 실패: ${virus}`,
        accessDenied: '본부 접근 거부: API Key 오류 또는 사용량 초과',
        dataSynced: '모든 구축 데이터가 Bunker 저장 노드와 동기화되었습니다',
        systemOffline: '뉴럴 클라우드 연결 해제 중. 데이터 물리 봉인 실행...',
        towerOnline: port => `신호 인터셉트 타워 온라인 [주파수: ${port}]`,
        linkSevered: '연결 종료: 네트워크 상태 또는 블랙박스 공명을 확인하십시오',
        star: '이 프로젝트가 시간을 절약해 준다면 GitHub에서 Star를 눌러주세요 ⭐',
        watchDesc: '전체 채널 연동 모니터링 시작: Page/Part/API 협동 구축 지원',
        disclaimer: '매칭 결과는 참고용이며 최종 판단은 각 기체가 실제 상황에 따라 조정해야 합니다',
        towerConnected: port => `명령: 프록시 대상을 http://localhost:${port} 로 설정하십시오`,
        networkInstability: count => `뉴럴 클라우드 연결 불안정. 재연결 시도 중... (${count}번째 시도)`,
        copyEnum: '│ Backend 원본 유전자(Enum) 발견\n│ 권장: 아래 코드를 해당 모듈 리소스 센터에 수동 적용하십시오',
        initComplete: cmd => `Bunker 배치 완료. 빠른 전장 진입을 위해 ${cmd} 를 package.json scripts에 추가하십시오`,
        frameworkNotSupported: template => `[${template}] 프레임워크는 아직 지원되지 않습니다. Pull Request 환영합니다`,
        strategicThreshold: (target, current) => `물리 복제 수가 전략 임계값 ${target}을 초과했습니다! 현재 전력: ${current}`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? '축하합니다 지휘관. 당신의 구축 프로토콜은 인류의 영광의 일부가 되었습니다' : `현재 구축 수: ${current}. 업적 달성까지 ${target - current}회 남았습니다`,
    },
    operator6O: {
        call2B: '2B 호출 완료. Bunker 전체 채널 연동 모니터링 시스템 준비 완료!',
    }
}