module.exports = {
    nineS: {
        dataCamouflageComplete: 'Geração de dados Mock concluída',
        scanningField: 'Analisando diferenças entre campos Frontend/Backend... Executando protocolo de ponte semântica',
        dataCamouflage: fileName => `Invadindo firewall do alvo... Executando protocolo de camuflagem de dados [${fileName}]`,
    },
    pod042: {
        extractingUiMetadata: 'Extraindo metadados de UI da rede neural em nuvem...',
        simulate: 'Requisição real detectada. Implantando pacote de simulação padrão: example.json',
        queueEmpty: 'Fila vazia. Sincronizando configuração de rotas Menu com o Bunker...',
        uploadVisualMetadata: 'Enviando metadados visuais ao comando central. Iniciando análise semântica...',
        visualPartCaptured: 'Fragmento visual detectado. Executando "Protocolo de Construção Fragmentada"...',
        partialConstruction: time => `Relatório: construção parcial concluída. Tempo: ${time}s`,
        partialRecommendation: '│ Recomendação: integre manualmente o bloco de código acima no arquivo alvo',
        constructionAborted: virus => `Construção interrompida. Vírus lógico ou tempo limite de conexão detectado: ${virus}`,
        partialConstructionAborted: virus => `[Aviso] Falha na construção fragmentada. Interferência lógica detectada: ${virus}`,
        visualCaptured: fileName => `Captura visual concluída: [${fileName}]. Alocando recursos do Bunker para construção física...`,
        intercept: fileName => `Módulo [${fileName}] já existe no banco de dados do Bunker. Protocolo de construção ignorado para evitar sobrescrita`,
        assemblyComplete: (fileName, time) => `Protocolo de construção finalizado. Módulo [${fileName}] instalado fisicamente. Tempo: ${time}s`,
    },
    pod153: {
        signalLinkFault: virus => `Falha no link de sinal: ${virus}`,
        formatError: 'Formato JSON fora do padrão detectado. Tentando alinhamento dos dados originais',
        autonomousAddressing: 'Iniciando "Protocolo de Endereçamento Autônomo de Todos os Canais [Versão Semântica]"...',
        signalSynchronized: count => `Sincronização concluída. ${count} nós energizados`,
        alignmentFailed: virus => `Falha no alinhamento do sinal. Dados da API bloqueados pelo firewall: ${virus}`,
        inactiveModule: fileName => `Módulo inativo encontrado [${fileName}]. Solicitando análise de alta precisão pelo 9S`,
        capturedRuntimeSignal: fileName => `Sinal de execução capturado [${fileName}]. Executando protocolo automático de alinhamento...`,
        reconEncryptedData: fileName => `Fonte de dados criptografada encontrada [${fileName}]. Tentando alinhamento semântico...`,
        unknownModule: fileName => `Recurso do módulo [${fileName}] não encontrado no banco do Bunker. Execute primeiro a construção visual`,
        bridgeProtocolComplete: (count, time) => `Protocolo de ponte semântica concluído. ${count} diferenças de campos corrigidas. Tempo: ${time}s`,
    },
    bunker: {
        exit: 'Sinal do sistema perdido...',
        envCopy: 'Arquivo .env salvo com sucesso',
        argDesc: 'Definir template do framework frontend',
        systemStandby: 'Sistema em modo de espera...',
        desc: 'Gerador de código CRUD frontend alimentado por IA',
        configCopy: 'Arquivo config.js salvo com sucesso',
        initDesc: 'Inicializar ambiente de construção do Bunker no diretório atual',
        envCheck: 'Arquivo .env existente encontrado. Criação ignorada',
        dataSynced: 'Todos os dados de construção foram sincronizados com o nó de armazenamento do Bunker',
        configCheck: 'Arquivo config.js existente encontrado. Criação ignorada',
        linkSevered: 'Conexão interrompida: verifique o estado da rede ou a ressonância do Black Box',
        systemOffline: 'Desconectando conexão neural em nuvem. Executando selamento físico dos dados...',
        copyTemplateError: virus => `Falha na construção do template: ${virus}`,
        star: 'Se este projeto ajudou você a economizar tempo, deixe uma estrela no GitHub ⭐',
        towerOnline: port => `Torre de interceptação de sinais online [Frequência: ${port}]`,
        watchDesc: 'Iniciar monitoramento de todos os canais: construção integrada de Page/Part/API',
        accessDenied: 'Acesso ao comando central negado: API Key inválida ou limite excedido',
        disclaimer: 'Os resultados de correspondência são apenas referências. Cada unidade deve ajustar conforme a situação real',
        towerConnected: port => `Comando: direcione seu proxy para http://localhost:${port}`,
        copyEnum: '│ Código genético original do Backend (Enum) detectado\n│ Recomendação: aplique manualmente o trecho abaixo no centro de recursos do módulo',
        networkInstability: count => `Instabilidade na conexão neural em nuvem. Tentando reconectar... (tentativa ${count})`,
        frameworkNotSupported: template => `Framework [${template}] ainda não suportado. Pull Requests são bem-vindos`,
        strategicThreshold: (target, current) => `Número de cópias físicas ultrapassou o limite estratégico ${target}! Poder atual: ${current}`,
        initComplete: cmd => `Implantação do Bunker concluída. Para acesso rápido ao campo de batalha, adicione ${cmd} aos scripts do package.json`,
        isLegendary: (unlockAchievement, current, target) =>
            unlockAchievement
                ? 'Parabéns comandante. Seu protocolo de construção tornou-se parte da glória da humanidade'
                : `Construções atuais: ${current}. Faltam ${target - current} operações para conquistar a medalha`,
    },
    operator6O: {
        call2B: 'Chamando 2B. Monitoramento global dos canais do Bunker pronto!',
    }
}