module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mock veri üretimi tamamlandı',
        scanningField: 'Frontend/Backend alan farklılıkları analiz ediliyor... Semantik köprü protokolü başlatılıyor',
        dataCamouflage: fileName => `Hedef güvenlik duvarı aşılıyor... Veri kamuflaj protokolü çalıştırılıyor [${fileName}]`,
    },
    pod042: {
        extractingUiMetadata: 'Bulut sinir ağından UI meta verileri çıkarılıyor...',
        simulate: 'Gerçek istek algılandı. Standart simülasyon paketi bırakılıyor: example.json',
        queueEmpty: 'Kuyruk boş. Menü rota yapılandırması Bunker ile senkronize ediliyor...',
        uploadVisualMetadata: 'Görsel meta veriler komuta merkezine gönderiliyor. Semantik analiz başlatılıyor...',
        visualPartCaptured: 'Görsel parça algılandı. Parçalı inşa protokolü başlatılıyor...',
        partialConstruction: time => `Rapor: Kısmi inşa tamamlandı. Süre: ${time}s`,
        partialRecommendation: '│ Öneri: Yukarıdaki kod bloğunu hedef dosyaya manuel olarak entegre edin',
        constructionAborted: virus => `İnşa durduruldu. Mantıksal virüs veya bağlantı zaman aşımı tespit edildi: ${virus}`,
        partialConstructionAborted: virus => `[Uyarı] Parçalı inşa başarısız. Mantıksal engel tespit edildi: ${virus}`,
        visualCaptured: fileName => `Görsel yakalama tamamlandı: [${fileName}]. Bunker kaynakları fiziksel inşa için hazırlanıyor...`,
        intercept: fileName => `[${fileName}] modülü Bunker veritabanında zaten mevcut. Veri kaybını önlemek için işlem atlandı`,
        assemblyComplete: (fileName, time) => `İnşa protokolü tamamlandı. [${fileName}] modülü fiziksel olarak kuruldu. Süre: ${time}s`,
    },
    pod153: {
        signalLinkFault: virus => `Sinyal bağlantı hatası: ${virus}`,
        formatError: 'Standart dışı JSON formatı. Ham veri hizalaması deneniyor',
        autonomousAddressing: 'Çok kanallı otonom adresleme protokolü [semantik sürüm] başlatılıyor...',
        signalSynchronized: count => `Sinyal senkronizasyonu tamamlandı. ${count} düğüm aktif edildi`,
        alignmentFailed: virus => `Sinyal hizalama başarısız. API verileri güvenlik duvarına takıldı: ${virus}`,
        inactiveModule: fileName => `[${fileName}] etkin olmayan modül bulundu. 9S yüksek hassasiyetli analiz talep ediyor`,
        capturedRuntimeSignal: fileName => `Çalışma zamanı sinyali yakalandı [${fileName}]. Otomatik hizalama başlatılıyor...`,
        reconEncryptedData: fileName => `Şifrelenmiş veri kaynağı bulundu [${fileName}]. Semantik hizalama deneniyor...`,
        unknownModule: fileName => `[${fileName}] modül kaynağı Bunker veritabanında bulunamadı. Önce görsel inşa gerçekleştirin`,
        bridgeProtocolComplete: (count, time) => `Semantik köprü protokolü tamamlandı. ${count} alan farkı düzeltildi. Süre: ${time}s`,
    },
    bunker: {
        exit: 'Sistem sinyali kaybedildi...',
        envCopy: '.env dosyası kaydedildi',
        argDesc: 'Frontend framework şablonunu belirt',
        systemStandby: 'Sistem bekleme modunda...',
        desc: 'Yapay zeka destekli frontend CRUD kod üreticisi',
        configCopy: 'config.js dosyası kaydedildi',
        initDesc: 'Mevcut dizinde Bunker inşa ortamını başlat',
        envCheck: '.env dosyası zaten mevcut. Oluşturma atlandı',
        dataSynced: 'Tüm inşa verileri Bunker depolama düğümü ile senkronize edildi',
        configCheck: 'config.js dosyası zaten mevcut. Oluşturma atlandı',
        linkSevered: 'Bağlantı kesildi: ağ durumunu veya Black Box rezonansını kontrol edin',
        systemOffline: 'Bulut sinir bağlantısı kesiliyor. Verilerin fiziksel mühürleme işlemi başlatılıyor...',
        copyTemplateError: virus => `Şablon inşası başarısız: ${virus}`,
        star: 'Bu proje size zaman kazandırdıysa GitHub üzerinde yıldız bırakın ⭐',
        towerOnline: port => `Sinyal yakalama kulesi aktif [Frekans: ${port}]`,
        watchDesc: 'Tam kanal izlemeyi başlat: Page/Part/API ortak inşası',
        accessDenied: 'Komuta merkezi erişimi reddetti: API Key geçersiz veya limit doldu',
        disclaimer: 'Eşleştirme sonuçları yalnızca referanstır. Birimler gerçek duruma göre ayarlama yapmalıdır',
        towerConnected: port => `Komut: Proxy hedefinizi http://localhost:${port} adresine yönlendirin`,
        copyEnum: '│ Backend genetik kodu (Enum) tespit edildi\n│ Öneri: Aşağıdaki kod parçasını modül kaynak merkezine manuel olarak ekleyin',
        networkInstability: count => `Bulut sinir ağı kararsız. Yeniden bağlanılıyor... (${count}. deneme)`,
        frameworkNotSupported: template => `Framework [${template}] henüz desteklenmiyor. Pull Request katkıları bekleniyor`,
        strategicThreshold: (target, current) => `Fiziksel kopya sayısı stratejik eşik ${target} değerini geçti! Mevcut güç: ${current}`,
        initComplete: cmd => `Bunker kurulumu tamamlandı. Hızlı erişim için ${cmd} komutunu package.json scripts bölümüne ekleyin`,
        isLegendary: (unlockAchievement, current, target) =>
            unlockAchievement
                ? 'Tebrikler komutan. İnşa protokolünüz insanlığın görkeminin bir parçası oldu'
                : `Mevcut inşa sayısı: ${current}. Madalyaya ulaşmak için ${target - current} işlem kaldı`,
    },
    operator6O: {
        call2B: '2B çağrılıyor. Bunker tüm kanal izleme sistemi hazır!',
    }
}