module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mock 数据生成成功',
        scanningField: '正在扫描前后端字段差异... 执行语义桥接任务',
        dataCamouflage: fileName => `正在突破目标防火墙... 执行数据伪装程序 [${fileName}]`,
    },
    pod042: {
        extractingUiMetadata: '正在从神经云网络提取 UI 元数据...',
        simulate: '拦截到实弹请求。正在空投标准模拟包: example.json',
        queueEmpty: '队列已空，正在向 Bunker 同步 Menu 路由配置...',
        uploadVisualMetadata: '正在上传视觉元数据至司令部进行语义分析...',
        visualPartCaptured: `侦测到局部视觉样本。正在执行“碎片构筑协议”...`,
        partialConstruction: time => `报告：局部构筑达成。耗时: ${time}s`,
        partialRecommendation: '│ 建议：请手动将上述代码块物理装配至您的目标文件中',
        constructionAborted: virus => `构筑中断。检测到逻辑病毒或连接超时：${virus}`,
        partialConstructionAborted: virus => `[警告] 碎片构筑失败。系统检测到逻辑干扰：${virus}`,
        visualCaptured: fileName => `视觉传感器捕捉完成: [${fileName}]。正在调配地堡资源进行物理构筑...`,
        intercept: fileName => `模块 [${fileName}] 已存在于地堡数据库中。为了防止数据覆盖，构筑协议已跳过`,
        assemblyComplete: (fileName, time) => `构筑协议执行完毕。模块 [${fileName}] 物理装配达成。耗时: ${time}s`,
    },
    pod153: {
        signalLinkFault: virus => `信号链路故障: ${virus}`,
        formatError: '数据格式非标准 JSON，将尝试原始字符对齐',
        autonomousAddressing: `启动‘全频道自动寻址协议 [语义扫描版]’...`,
        signalSynchronized: count => `信号同步完成，${count} 个节点已通电`,
        alignmentFailed: virus => `信号对齐失败。接口数据遭遇强力防火墙：${virus}`,
        inactiveModule: fileName => `发现未通电模块 [${fileName}]，请求 9S 执行高精度对账...`,
        capturedRuntimeSignal: fileName => `截获运行时信号 [${fileName}]。执行自动对齐协议...`,
        reconEncryptedData: fileName => `发现加密数据源 [${fileName}]。正在尝试执行语义对齐协议...`,
        unknownModule: fileName => `地堡数据库中未检索到模块 [${fileName}] 的资源文件。请先执行视觉构筑`,
        bridgeProtocolComplete: (count, time) => `语义桥接协议执行完毕。已物理修正 ${count} 处字段偏差。耗时: ${time}s`,
    },
    bunker: {
        exit: '系统信号已丢失',
        envCopy: '.env 存储完毕',
        argDesc: '指定前端框架模板',
        systemStandby: '系统待机中...',
        desc: 'AI驱动的前端CRUD代码生成器',
        configCopy: 'config.js 存储完毕',
        initDesc: '在当前目录初始化地堡构筑环境',
        envCheck: '终端已存在 .env 文件，跳过生成',
        dataSynced: '所有构筑数据已同步至 Bunker 存储节点',
        configCheck: '终端已存在 config.js 文件，跳过生成',
        linkSevered: '连接中断：请检查网络状态或黑盒共鸣情况',
        systemOffline: '正在断开神经云链接,执行数据物理封存...',
        copyTemplateError: virus => `模板构筑失败: ${virus}`,
        star: '如果它能帮您节省时间，请在 GitHub 上给它点个赞 ⭐',
        towerOnline: port => `信号拦截塔已在线 [波段: ${port}]`,
        watchDesc: '开启全频道联动监控：支持 Page/Part/API 协同构筑',
        accessDenied: '司令部拒绝访问：API Key 无效或额度耗尽，请检查！',
        disclaimer: '匹配结果仅供参考，不构成最终决策，各机体需根据实际情况进行调整',
        towerConnected: port => `指令：请将您的代理目标指向 http://localhost:${port}`,
        networkInstability: count => `神经云网络连接不稳，正在尝试重新链接... (第 ${count} 次重试)`,
        frameworkNotSupported: template => `暂不支持 [${template}] 框架。欢迎提交 Pull Request 贡献`,
        strategicThreshold: (target, current) => `物理克隆总数已超越 ${target} 战略阈值！当前战力：${current}`,
        initComplete: cmd => `地堡部署完毕, 为了更快捷地进入战场，建议手动执行 [物理装配]: 将 ${cmd} 加入您的 package.json scripts 中`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? '恭喜您指挥官，您的构筑协议已成为人类荣光的一部分' : `当前构筑总数：${current}。距离 ${target} 勋章还剩 ${target - current} 次`,
    },
    operator6O: {
        call2B: '呼叫 2B，地堡全频道联动监控已就绪！',
    }
}