module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mock 資料生成成功',
        scanningField: '正在掃描前後端欄位差異... 執行語意橋接任務',
        dataCamouflage: fileName => `正在突破目標防火牆... 執行資料偽裝程序 [${fileName}]`,
    },
    pod042: {
        startScout: '啟動【右鍵一鍵快照】模式...',
        capturedToast: '圖像情報已擷取，開始傳輸...',
        extractingUiMetadata: '正在從神經雲網路提取 UI 中繼資料...',
        simulate: '攔截到實際請求。正在空投標準模擬包: example.json',
        partialConstruction: time => `報告：局部構築完成。耗時: ${time}s`,
        visualPartCaptured: '偵測到局部視覺樣本。正在執行「碎片構築協議」...',
        partialRecommendation: '│ 建議：請手動將上述程式碼區塊整合至目標檔案',
        uploadVisualMetadata: '正在上傳視覺中繼資料至司令部，執行語意分析...',
        scoutReady: '【右鍵快照模式就緒】在瀏覽器頁面任意位置點擊【滑鼠右鍵】即可秒截屏',
        constructionAborted: virus => `構築中斷。偵測到邏輯病毒或連線逾時：${virus}`,
        capturedPage: pageName => `擷取頁面【${pageName}】-> 已投遞至 screenShot 目錄`,
        partialConstructionAborted: virus => `[警告] 碎片構築失敗。系統偵測到邏輯干擾：${virus}`,
        intercept: fileName => `模組 [${fileName}] 已存在於 Bunker 資料庫中。為避免資料覆蓋，構築協議已跳過`,
        visualCaptured: fileName => `視覺感測器捕捉完成: [${fileName}]。正在調配 Bunker 資源進行物理構築...`,
        assemblyComplete: (fileName, time) => `構築協議執行完成。模組 [${fileName}] 已完成物理裝配。耗時: ${time}s，開始同步 Menu 路由設定...`,
    },
    pod153: {
        signalLinkFault: virus => `訊號鏈路故障: ${virus}`,
        formatError: '資料格式非標準 JSON，將嘗試原始字串對齊',
        autonomousAddressing: '啟動「全頻道自動尋址協議 [語意掃描版]」...',
        signalSynchronized: count => `訊號同步完成，${count} 個節點已通電`,
        alignmentFailed: virus => `訊號對齊失敗。API 資料遭遇強力防火牆：${virus}`,
        inactiveModule: fileName => `發現未通電模組 [${fileName}]，請求 9S 執行高精度對帳...`,
        capturedRuntimeSignal: fileName => `截獲執行時訊號 [${fileName}]。執行自動對齊協議...`,
        reconEncryptedData: fileName => `發現加密資料源 [${fileName}]。正在嘗試執行語意對齊協議...`,
        unknownModule: fileName => `Bunker 資料庫中未找到模組 [${fileName}] 的資源檔案。請先執行視覺構築`,
        bridgeProtocolComplete: (count, time) => `語意橋接協議執行完成。已修正 ${count} 處欄位差異。耗時: ${time}s`,
    },
    bunker: {
        exit: '系統訊號已遺失...',
        envCopy: '.env 儲存完成',
        argDesc: '指定前端框架模板',
        systemStandby: '系統待命中...',
        desc: 'AI 驅動的前端 CRUD 程式碼生成器',
        configCopy: 'config.js 儲存完成',
        initDesc: '在目前目錄初始化 Bunker 構築環境',
        envCheck: '終端已存在 .env 檔案，跳過生成',
        dataSynced: '所有構築資料已同步至 Bunker 儲存節點',
        configCheck: '終端已存在 config.js 檔案，跳過生成',
        linkSevered: '連線中斷：請檢查網路狀態或黑盒共鳴情況',
        systemOffline: '正在斷開神經雲連結，執行資料物理封存...',
        copyTemplateError: virus => `模板構築失敗: ${virus}`,
        star: '如果它能幫助您節省時間，請在 GitHub 上給它一顆 Star ⭐',
        towerOnline: port => `訊號攔截塔已上線 [頻段: ${port}]`,
        watchDesc: '開啟全頻道聯動監控：支援 Page/Part/API 協同構築',
        accessDenied: '司令部拒絕存取：API Key 無效或額度耗盡，請檢查！',
        disclaimer: '匹配結果僅供參考，不構成最終決策，各機體需依照實際情況進行調整',
        towerConnected: port => `指令：請將您的代理目標指向 http://localhost:${port}`,
        copyEnum: '│ 偵測到後端原始基因(Enum)\n│ 建議：將下方程式碼片段手動焊接至該模組資源中心',
        networkInstability: count => `神經雲網路連線不穩定，正在嘗試重新連線... (第 ${count} 次重試)`,
        frameworkNotSupported: template => `暫不支援 [${template}] 框架。歡迎提交 Pull Request 貢獻`,
        strategicThreshold: (target, current) => `物理複製總數已超越 ${target} 戰略閾值！目前戰力：${current}`,
        initComplete: cmd => `Bunker 部署完成，為更快速進入戰場，建議手動將 ${cmd} 加入 package.json scripts`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? '恭喜您指揮官，您的構築協議已成為人類榮光的一部分' : `目前構築總數：${current}。距離 ${target} 徽章還剩 ${target - current} 次`,
    },
    operator6O: {
        call2B: '呼叫 2B，Bunker 全頻道聯動監控已準備完成！',
    }
}