name: GitHub Repo Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# 💡 在这里全局开启 Node.js 24 强制模式，消灭警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v4 # 已经是最新版

      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.4.1
        with:
          repository: ${{ github.repository }}
          ghtoken: ${{ secrets.STATS_TOKEN }}
          databranch: github-repo-stats

      - name: Clean and Format Stats Branch
        run: |
          git fetch origin github-repo-stats
          git checkout github-repo-stats

          mkdir -p ../temp_backup
          REPORT_DIR=$(find . -type d -name "latest-report" | head -n 1)
          DATA_DIR=$(find . -type d -name "ghrs-data" | head -n 1)
          PLOT_DIR=$(find . -type d -name "plots" | head -n 1)

          if [ -d "$REPORT_DIR" ]; then sudo cp -r $REPORT_DIR/* ../temp_backup/; fi
          if [ -d "$DATA_DIR" ]; then sudo cp -r $DATA_DIR ../temp_backup/; fi
          if [ -d "$PLOT_DIR" ]; then sudo cp -r $PLOT_DIR ../temp_backup/; fi

          sudo rm -rf *
          sudo rm -rf .github .env.example .gitignore .npmignore
          sudo cp -r ../temp_backup/* .
          if [ -f "report.md" ]; then sudo mv report.md README.md; fi
          sudo chown -R runner:docker .

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "style: clean stable stats with node24" || echo "no changes"
          git push origin github-repo-stats --force
