module.exports = {
    nineS: {
        dataCamouflageComplete: 'Pembuatan data Mock berhasil',
        scanningField: 'Memindai perbedaan field Frontend/Backend... Menjalankan protokol jembatan semantik',
        dataCamouflage: fileName => `Menembus firewall target... Menjalankan protokol penyamaran data [${fileName}]`,
    },
    pod042: {
        startScout: 'Mengaktifkan mode [Jepretan Taktis Klik-Kanan]...',
        capturedToast: 'Intelijen visual ditangkap. Memulai transmisi...',
        extractingUiMetadata: 'Mengekstrak metadata UI dari jaringan saraf cloud...',
        partialConstruction: time => `Laporan: konstruksi parsial selesai. Waktu: ${time}s`,
        simulate: 'Permintaan nyata terdeteksi. Menurunkan paket simulasi standar: example.json',
        visualPartCaptured: 'Sampel visual terdeteksi. Menjalankan protokol konstruksi fragmen...',
        uploadVisualMetadata: 'Mengirim metadata visual ke pusat komando untuk analisis semantik...',
        partialRecommendation: '│ Rekomendasi: Pasang blok kode di atas secara manual ke file target',
        capturedPage: pageName => `Halaman ditangkap [${pageName}] -> Ditransmisikan ke direktori mission`,
        scoutReady: '[Mode Jepretan Klik-Kanan Siap] Klik kanan di mana saja pada halaman web untuk mengambil gambar.',
        constructionAborted: virus => `Konstruksi dihentikan. Virus logika atau batas waktu koneksi terdeteksi: ${virus}`,
        partialConstructionAborted: virus => `[Peringatan] Konstruksi fragmen gagal. Gangguan logika terdeteksi: ${virus}`,
        intercept: fileName => `Modul [${fileName}] sudah ada dalam database Bunker. Protokol dilewati untuk mencegah penimpaan`,
        visualCaptured: fileName => `Penangkapan visual selesai: [${fileName}]. Menyiapkan sumber daya Bunker untuk konstruksi fisik...`,
        assemblyComplete: (fileName, time) => `Protokol konstruksi selesai. Modul [${fileName}] berhasil dirakit secara fisik. Waktu: ${time}s, Sinkronisasi konfigurasi Menu dengan Bunker...`,
    },
    pod153: {
        signalLinkFault: virus => `Gangguan koneksi sinyal: ${virus}`,
        signalSynchronized: count => `Sinkronisasi sinyal selesai. ${count} node telah diaktifkan`,
        alignmentFailed: virus => `Penyelarasan sinyal gagal. Data API menghadapi firewall: ${virus}`,
        autonomousAddressing: 'Memulai protokol pengalamatan otomatis multi-kanal [versi semantik]...',
        inactiveModule: fileName => `Modul tidak aktif ditemukan [${fileName}]. Meminta analisis presisi tinggi dari 9S`,
        capturedRuntimeSignal: fileName => `Sinyal runtime tertangkap [${fileName}]. Menjalankan penyelarasan otomatis...`,
        reconEncryptedData: fileName => `Sumber data terenkripsi ditemukan [${fileName}]. Mencoba protokol penyelarasan semantik...`,
        bridgeProtocolComplete: (count, time) => `Protokol jembatan semantik selesai. ${count} perbedaan field telah diperbaiki. Waktu: ${time}s`,
        unknownModule: fileName => `Resource modul [${fileName}] tidak ditemukan dalam database Bunker. Jalankan konstruksi visual terlebih dahulu`,
    },
    bunker: {
        exit: 'Sinyal sistem telah hilang...',
        envCopy: 'File .env berhasil disimpan',
        systemStandby: 'Sistem dalam mode standby...',
        configCopy: 'File config.js berhasil disimpan',
        desc: 'Generator kode CRUD frontend berbasis AI',
        argDesc: 'Menentukan template framework frontend',
        envCheck: 'File .env sudah tersedia. Pembuatan dilewati',
        configCheck: 'File config.js sudah tersedia. Pembuatan dilewati',
        copyTemplateError: virus => `Konstruksi template gagal: ${virus}`,
        linkSevered: 'Koneksi terputus: periksa jaringan atau resonansi Black Box',
        towerOnline: port => `Menara intersepsi sinyal aktif [Frekuensi: ${port}]`,
        initDesc: 'Menginisialisasi lingkungan konstruksi Bunker di direktori saat ini',
        accessDenied: 'Akses ditolak pusat komando: API Key tidak valid atau kuota habis',
        bootDesc: 'Mengaktifkan pemantauan multi-kanal: konstruksi Page/Part/API terpadu',
        star: 'Jika proyek ini membantu menghemat waktu Anda, berikan bintang di GitHub ⭐',
        systemOffline: 'Memutus koneksi neural cloud. Menjalankan penyegelan fisik data...',
        dataSynced: 'Seluruh data konstruksi telah disinkronkan dengan node penyimpanan Bunker',
        towerConnected: port => `Perintah: arahkan target proxy Anda ke http://localhost:${port}`,
        frameworkNotSupported: template => `Framework [${template}] belum didukung. Pull Request sangat diterima`,
        disclaimer: 'Hasil pencocokan hanya sebagai referensi. Setiap unit harus menyesuaikan dengan kondisi nyata',
        initComplete: cmd => `Deploy Bunker selesai. Tambahkan ${cmd} ke scripts package.json untuk akses lebih cepat`,
        networkInstability: count => `Jaringan neural cloud tidak stabil. Mencoba koneksi ulang... (percobaan ${count})`,
        copyEnum: '│ Kode genetik backend asli (Enum) terdeteksi\n│ Rekomendasi: pasang potongan kode berikut ke pusat resource modul',
        strategicThreshold: (target, current) => `Jumlah konstruksi telah melewati ambang strategis ${target}! Kekuatan saat ini: ${current}`,
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? 'Selamat komandan. Protokol konstruksi Anda telah menjadi bagian dari kejayaan umat manusia' : `Jumlah konstruksi saat ini: ${current}. Tersisa ${target - current} operasi menuju medali`,
    },
    operator6O: {
        call2B: 'Memanggil 2B. Sistem pemantauan seluruh kanal Bunker siap!',
    }
}