module.exports = {
    nineS: {
        dataCamouflageComplete: 'Mock veri üretimi tamamlandı',
        scanningField: 'Frontend/Backend alan farklılıkları analiz ediliyor... Semantik köprü protokolü başlatılıyor',
        dataCamouflage: fileName => `Hedef güvenlik duvarı aşılıyor... Veri kamuflaj protokolü çalıştırılıyor [${fileName}]`,
    },
    pod042: {
        capturedToast: 'Görsel istihbarat yakalandı. Aktarım başlatılıyor...',
        startScout: '[Taktik Sağ Tık Anlık Görüntü] modu etkinleştiriliyor...',
        partialConstruction: time => `Rapor: Kısmi inşa tamamlandı. Süre: ${time}s`,
        extractingUiMetadata: 'Bulut sinir ağından UI meta verileri çıkarılıyor...',
        visualPartCaptured: 'Görsel parça algılandı. Parçalı inşa protokolü başlatılıyor...',
        capturedPage: pageName => `Sayfa yakalandı [${pageName}] -> mission dizinine aktarıldı`,
        simulate: 'Gerçek istek algılandı. Standart simülasyon paketi bırakılıyor: example.json',
        partialRecommendation: '│ Öneri: Yukarıdaki kod bloğunu hedef dosyaya manuel olarak entegre edin',
        uploadVisualMetadata: 'Görsel meta veriler komuta merkezine gönderiliyor. Semantik analiz başlatılıyor...',
        partialConstructionAborted: virus => `[Uyarı] Parçalı inşa başarısız. Mantıksal engel tespit edildi: ${virus}`,
        constructionAborted: virus => `İnşa durduruldu. Mantıksal virüs veya bağlantı zaman aşımı tespit edildi: ${virus}`,
        scoutReady: '[Sağ Tık Anlık Görüntü Modu Hazır] Anında yakalamak için web sayfasında herhangi bir yere sağ tıklayın.',
        intercept: fileName => `[${fileName}] modülü Bunker veritabanında zaten mevcut. Veri kaybını önlemek için işlem atlandı`,
        visualCaptured: fileName => `Görsel yakalama tamamlandı: [${fileName}]. Bunker kaynakları fiziksel inşa için hazırlanıyor...`,
        assemblyComplete: (fileName, time) => `İnşa protokolü tamamlandı. [${fileName}] modülü fiziksel olarak kuruldu. Süre: ${time}s, Menü rota yapılandırması Bunker ile senkronize ediliyor...`,
    },
    pod153: {
        signalLinkFault: virus => `Sinyal bağlantı hatası: ${virus}`,
        signalSynchronized: count => `Sinyal senkronizasyonu tamamlandı. ${count} düğüm aktif edildi`,
        autonomousAddressing: 'Çok kanallı otonom adresleme protokolü [semantik sürüm] başlatılıyor...',
        alignmentFailed: virus => `Sinyal hizalama başarısız. API verileri güvenlik duvarına takıldı: ${virus}`,
        reconEncryptedData: fileName => `Şifrelenmiş veri kaynağı bulundu [${fileName}]. Semantik hizalama deneniyor...`,
        inactiveModule: fileName => `[${fileName}] etkin olmayan modül bulundu. 9S yüksek hassasiyetli analiz talep ediyor`,
        capturedRuntimeSignal: fileName => `Çalışma zamanı sinyali yakalandı [${fileName}]. Otomatik hizalama başlatılıyor...`,
        unknownModule: fileName => `[${fileName}] modül kaynağı Bunker veritabanında bulunamadı. Önce görsel inşa gerçekleştirin`,
        bridgeProtocolComplete: (count, time) => `Semantik köprü protokolü tamamlandı. ${count} alan farkı düzeltildi. Süre: ${time}s`,
    },
    bunker: {
        exit: 'Sistem sinyali kaybedildi...',
        envCopy: '.env dosyası kaydedildi',
        systemStandby: 'Sistem bekleme modunda...',
        configCopy: 'config.js dosyası kaydedildi',
        argDesc: 'Frontend framework şablonunu belirt',
        initDesc: 'Mevcut dizinde Bunker inşa ortamını başlat',
        desc: 'Yapay zeka destekli frontend CRUD kod üreticisi',
        envCheck: '.env dosyası zaten mevcut. Oluşturma atlandı',
        copyTemplateError: virus => `Şablon inşası başarısız: ${virus}`,
        configCheck: 'config.js dosyası zaten mevcut. Oluşturma atlandı',
        bootDesc: 'Tam kanal izlemeyi başlat: Page/Part/API ortak inşası',
        towerOnline: port => `Sinyal yakalama kulesi aktif [Frekans: ${port}]`,
        star: 'Bu proje size zaman kazandırdıysa GitHub üzerinde yıldız bırakın ⭐',
        dataSynced: 'Tüm inşa verileri Bunker depolama düğümü ile senkronize edildi',
        accessDenied: 'Komuta merkezi erişimi reddetti: API Key geçersiz veya limit doldu',
        linkSevered: 'Bağlantı kesildi: ağ durumunu veya Black Box rezonansını kontrol edin',
        towerConnected: port => `Komut: Proxy hedefinizi http://localhost:${port} adresine yönlendirin`,
        networkInstability: count => `Bulut sinir ağı kararsız. Yeniden bağlanılıyor... (${count}. deneme)`,
        systemOffline: 'Bulut sinir bağlantısı kesiliyor. Verilerin fiziksel mühürleme işlemi başlatılıyor...',
        disclaimer: 'Eşleştirme sonuçları yalnızca referanstır. Birimler gerçek duruma göre ayarlama yapmalıdır',
        frameworkNotSupported: template => `Framework [${template}] henüz desteklenmiyor. Pull Request katkıları bekleniyor`,
        initComplete: cmd => `Bunker kurulumu tamamlandı. Hızlı erişim için ${cmd} komutunu package.json scripts bölümüne ekleyin`,
        strategicThreshold: (target, current) => `Fiziksel kopya sayısı stratejik eşik ${target} değerini geçti! Mevcut güç: ${current}`,
        copyEnum: '│ Backend genetik kodu (Enum) tespit edildi\n│ Öneri: Aşağıdaki kod parçasını modül kaynak merkezine manuel olarak ekleyin',
        isLegendary: (unlockAchievement, current, target) => unlockAchievement ? 'Tebrikler komutan. İnşa protokolünüz insanlığın görkeminin bir parçası oldu' : `Mevcut inşa sayısı: ${current}. Madalyaya ulaşmak için ${target - current} işlem kaldı`,
    },
    operator6O: {
        call2B: '2B çağrılıyor. Bunker tüm kanal izleme sistemi hazır!',
    }
}